version: '3'
services:
  mongodb:
    container_name: rest_mongo
    image: mongo
    restart: always
    ports:
      - '27017'
    logging:
      driver: 'none'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest_mongo_main_app
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://rest_mongo:27017/development
      - JWT_SECRET=&5678dh_z8765%__&%zz
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
